Repository nol-jo/nolzo-ticket-backend, pull requests merged in 2025-06, with the labels that each got.

#10 [Feature] 결제 데이터 추가기능 구현
  src/main/java/com/noljo/nolzo/payment/controller/PaymentController.java
  src/main/java/com/noljo/nolzo/payment/dto/PaymentRequest.java
  src/main/java/com/noljo/nolzo/payment/dto/PaymentResponse.java
  src/main/java/com/noljo/nolzo/payment/entity/Payment.java
  src/main/java/com/noljo/nolzo/payment/entity/PaymentMethod.java
  src/main/java/com/noljo/nolzo/payment/repository/PaymentRepository.java
  src/main/java/com/noljo/nolzo/payment/service/PaymentService.java
  src/main/java/com/noljo/nolzo/reservation/repository/ReservationRepository.java
  src/main/java/com/noljo/nolzo/ticket/dto/TicketResponse.java
  src/test/java/com/noljo/nolzo/domain/payment/service/PaymentServiceTest.java
  src/test/java/com/noljo/nolzo/support/fixture/PaymentFixture.java
Labels: enhancement

#25 [Feature] 이벤트 예약기능 구현
  src/main/java/com/noljo/nolzo/reservation/controller/ReservationController.java
  src/main/java/com/noljo/nolzo/reservation/dto/ReservationRequest.java
  src/main/java/com/noljo/nolzo/reservation/dto/ReservationResponse.java
  src/main/java/com/noljo/nolzo/reservation/entity/Reservation.java
  src/main/java/com/noljo/nolzo/reservation/service/ReservationService.java
  src/main/java/com/noljo/nolzo/seat/entity/Seat.java
  src/main/java/com/noljo/nolzo/seat/entity/SeatStatus.java
  src/main/java/com/noljo/nolzo/seat/repository/SeatRepository.java
  src/main/java/com/noljo/nolzo/seat/service/SeatService.java
  src/test/java/com/noljo/nolzo/domain/reservation/service/ReservationServiceTest.java
  src/test/java/com/noljo/nolzo/support/fixture/MemberFixture.java
  src/test/java/com/noljo/nolzo/support/fixture/ReservationFixture.java
  src/test/java/com/noljo/nolzo/support/fixture/SeatFixture.java
Labels: documentation

#34 [Feature] 날짜 및 시간 선택 기능 구현
  src/main/java/com/noljo/nolzo/reservation/controller/ReservationController.java
  src/main/java/com/noljo/nolzo/reservation/dto/EventDateTimeResponse.java
  src/main/java/com/noljo/nolzo/reservation/entity/Reservation.java
  src/main/java/com/noljo/nolzo/reservation/service/ReservationService.java
  src/test/java/com/noljo/nolzo/domain/Reservation/service/ReservationServiceTest.java
  src/test/java/com/noljo/nolzo/support/fixture/EventFixture.java
  src/test/java/com/noljo/nolzo/support/fixture/ReservationFixture.java
Labels: enhancement

#42 [Feature] 관람완료 목록 조회 기능 구현
  src/main/java/com/noljo/nolzo/reservation/controller/ReservationController.java
  src/main/java/com/noljo/nolzo/reservation/repository/ReservationRepository.java
  src/main/java/com/noljo/nolzo/reservation/service/ReservationService.java
Labels: enhancement

#50 [Refactor] 날짜 및 시간 선택 예외 사항 추가 리팩토링
  src/main/java/com/noljo/nolzo/reservation/controller/ReservationController.java
  src/main/java/com/noljo/nolzo/reservation/service/ReservationService.java
  src/test/java/com/noljo/nolzo/domain/reservation/service/ReservationServiceTest.java
Labels: refactor

#51 [Feature] 예약 취소 목록 조회 기능 구현
  src/main/java/com/noljo/nolzo/reservation/controller/ReservationController.java
  src/main/java/com/noljo/nolzo/reservation/repository/ReservationRepository.java
  src/main/java/com/noljo/nolzo/reservation/service/ReservationService.java
Labels: enhancement

#59 [Feature] 키워드 기반 이벤트 검색 기능 구현
  src/main/java/com/noljo/nolzo/event/controller/EventController.java
  src/main/java/com/noljo/nolzo/event/repository/EventRepository.java
  src/main/java/com/noljo/nolzo/event/service/EventService.java
Labels: enhancement

#47 [Feature] 회원 단건 조회 API 구현
  src/main/java/com/noljo/nolzo/member/controller/MemberController.java
  src/main/java/com/noljo/nolzo/member/dto/MemberDto.java
  src/main/java/com/noljo/nolzo/member/service/MemberService.java
Labels: enhancement

#49 [Feature] 회원 비밀번호 변경 API 구현
  src/main/java/com/noljo/nolzo/member/controller/MemberController.java
  src/main/java/com/noljo/nolzo/member/dto/PasswordChangeRequest.java
  src/main/java/com/noljo/nolzo/member/entity/Member.java
  src/main/java/com/noljo/nolzo/member/service/MemberService.java
Labels: enhancement

#61 [Feature] 회원 탈퇴 기능 추가
  src/main/java/com/noljo/nolzo/member/controller/MemberController.java
  src/main/java/com/noljo/nolzo/member/service/MemberService.java
Labels: enhancement

#66 [Feature] 조회수 기반 상위 10개 이벤트 조회 기능 구현
  src/main/java/com/noljo/nolzo/event/controller/EventController.java
  src/main/java/com/noljo/nolzo/event/dto/EventResponse.java
  src/main/java/com/noljo/nolzo/event/entity/Event.java
  src/main/java/com/noljo/nolzo/event/entity/EventCategory.java
  src/main/java/com/noljo/nolzo/event/repository/EventRepository.java
  src/main/java/com/noljo/nolzo/event/service/EventService.java
  src/test/java/com/noljo/nolzo/domain/event/service/EventServiceTest.java
Labels: enhancement

#72 [Feature] 파일 서버 AWS S3 연결 및 관련 로직 구현
  .gitignore
  build.gradle
  src/main/java/com/noljo/nolzo/event/controller/EventController.java
  src/main/java/com/noljo/nolzo/event/dto/EventRequest.java
  src/main/java/com/noljo/nolzo/event/entity/Event.java
  src/main/java/com/noljo/nolzo/event/service/EventService.java
  src/main/java/com/noljo/nolzo/global/config/S3Config.java
  src/main/java/com/noljo/nolzo/global/upload/S3Uploader.java
  src/main/resources/application.yml
Labels: enhancement

#74 [Refactor] 키워드 기반 이벤트 조회 로직 수정
  src/main/java/com/noljo/nolzo/event/repository/EventRepository.java
  src/main/java/com/noljo/nolzo/event/service/EventService.java
  src/test/java/com/noljo/nolzo/domain/event/service/EventServiceTest.java
Labels: refactor

#88 fix : 엔티티 누락 매핑 문제 해결에 따른 테스트 코드 변경
  src/test/java/com/noljo/nolzo/domain/reservation/service/ReservationServiceTest.java
Labels: bug

#97 [Fix] 이벤트 정보 및 스케줄 정보 수정 로직 테스트 코드 수정
  src/main/java/com/noljo/nolzo/event/dto/EventResponse.java
  src/main/java/com/noljo/nolzo/event/dto/EventUpdateRequest.java
  src/main/java/com/noljo/nolzo/schedule/dto/ScheduleResponse.java
  src/main/java/com/noljo/nolzo/schedule/dto/internal/ScheduleInfo.java
  src/test/java/com/noljo/nolzo/domain/event/service/EventServiceTest.java
  src/test/java/com/noljo/nolzo/support/fixture/EventFixture.java
Labels: bug

#98 [Fix] JPA Lazy 로딩과 JSON 직렬화 순환참조 문제 해결
  src/main/java/com/noljo/nolzo/reservation/controller/ReservationController.java
  src/main/java/com/noljo/nolzo/reservation/dto/ReservationDetail.java
  src/main/java/com/noljo/nolzo/reservation/repository/ReservationRepository.java
  src/main/java/com/noljo/nolzo/reservation/service/ReservationService.java
Labels: bug
